server:
  port: 8080

spring:
  neo4j:
    uri: neo4j://localhost:7999
    authentication:
      username: neo4j
      password: Adminn@AA312

logging:
  level:
    org:
      neo4j:
        driver:
          Driver: debug
          GraphDatabase: debug
